language: php
dist: xenial

services:
  - mysql

php:
  - 7.4
  - 8.0
  - 8.1

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1

cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

branches:
  only:
    - /[0-9]+\.x/

mysql:
  database: rules_finder
  username: root
  encoding: utf8

before_install:
  - source ./scripts/travis/01-setup-environment.sh

script:
  # Installing RulesFinder is the actual test
  - bash -x -e ./scripts/travis/02-install-rules-finder.sh